// This file is auto-generated by scripts/generateChangelog.js. Do not edit directly.
window.HM_CHANGELOG = [
    {
        "hash": "5128e52",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "fix(android): resolve silent native TTS on devices and unpin release links",
        "body": "- Add <queries> intent filter for android.intent.action.TTS_SERVICE in AndroidManifest to satisfy Android 11+ (API 30+) package visibility requirements\n- Eagerly initialize TextToSpeech in MainActivity onCreate to fix deadlock where JS awaited isReady() before calling speak\n- Implement queued utterance handling (pendingText) in native bridge so speech triggered while engine binds is not lost\n- Configure AudioAttributes.USAGE_MEDIA and CONTENT_TYPE_SPEECH to route TTS voice output to the media volume stream\n- Add multi-tier locale fallback (ms_MY -> ms -> US) so devices lacking offline Malay voice packs do not fail silently\n- Forward playback rate (this._speed) to native bridge tts.setSpeechRate(rate) and handle full UtteranceProgressListener lifecycle (onDone, onError, onStop)\n- Update README download badges and callout links to point directly to :latest release rather than pinned version tags\n- Expand Playwright tests in tts-bridge.spec.js to cover playback rate forwarding, async readiness, and speech stop\n- Bump service worker cache to v1.1.8 and Android versionCode 4 (1.0.3)"
    },
    {
        "hash": "17e2eba",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "docs: point APK download links to v1.0.2 release",
        "body": ""
    },
    {
        "hash": "e1bb8be",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "fix(android): bridge native TTS for APK narration",
        "body": "- Android WebView does not implement the Web Speech API (speechSynthesis is a silent stub), so narration never played in the APK\n- Add TextToSpeech bridge in MainActivity via @JavascriptInterface (window.AndroidTTS) with en-US/ms-MY locales, QUEUE_FLUSH and onDone JS callback\n- _speak() now prefers window.AndroidTTS and falls back to window.speechSynthesis on web; add _stopSpeech() shared by narrate toggle and auto stop\n- Bump sw.js cache to v1.1.7 and Android versionCode 3 (1.0.2); add Playwright spec asserting _speak routes through the native bridge\n- Validated: playwright tts-bridge + ui-info-fullscreen-auto suites pass; assembleRelease builds and signs successfully"
    },
    {
        "hash": "5ce3455",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "fix(android): enable hardware acceleration, canvas touch-action, and fix skeleton update for Kids Mode",
        "body": ""
    },
    {
        "hash": "2077267",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "docs: add release badges and direct APK download links to README",
        "body": ""
    },
    {
        "hash": "61ed93f",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "chore: sync changelog for v1.0.0",
        "body": ""
    },
    {
        "hash": "68c4e47",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "chore: ignore *.apk and *.aab in .gitignore",
        "body": ""
    },
    {
        "hash": "462c8ba",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "chore: update changelog on main",
        "body": ""
    },
    {
        "hash": "cdce456",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "docs(readme): collapse android apk section into details dropdown",
        "body": ""
    },
    {
        "hash": "aa9844c",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "feat(android): wire release signing config via keystore.properties",
        "body": ""
    },
    {
        "hash": "3be508d",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "docs: add android apk build, versioning and signing guide",
        "body": "- README section covering prerequisites, build commands, app identity, version bump guidance and release signing wiring\n- update project structure tree with android/, scripts/ and capacitor.config.json\n- regenerate js/changelog.js from git history"
    },
    {
        "hash": "8b1fd43",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "fix(js): skip pwa-only install ui in native capacitor app",
        "body": "- skip service-worker registration when window.Capacitor reports a native platform; local bundled assets have nothing to cache\n- suppress the PWA install widget under native platform detection while keeping its event wiring intact\n- web behavior unchanged: all 77 Playwright tests pass"
    },
    {
        "hash": "a460e6a",
        "date": "2026-09-09",
        "author": "bizzkoot",
        "subject": "feat(android): package app as installable apk via capacitor",
        "body": "- add Capacitor 8 (core/cli/android) with appId com.handmath.app serving staged www/\n- stage runtime-only web files via scripts/prepare-www.js, excluding ~25MB of unused model archives at the assets root\n- add npm scripts cap:prepare, cap:sync, android:apk, android:apk-release (builds with JDK 21 via brew keg fallback)\n- brand launcher icons, adaptive-icon foregrounds and splash screens from assets/icons/icon.svg (scripts/generate-android-icons.js)\n- ignore generated www/, gradle caches, copied web assets and signing credentials\n- verified: app-debug.apk builds, installs and launches on Pixel_6_API_34 emulator"
    },
    {
        "hash": "5cc9ece",
        "date": "2026-07-12",
        "author": "bizzkoot",
        "subject": "fix(challenge): unify arithmetic and limit checks",
        "body": "- Replace \"Show X\" tiers in L1-5 with generated addition/subtraction problems.\n- Show 5-choice grid for all levels, keeping hand controls active for L1-5.\n- Fix math generators to strictly enforce `opMax` on operands and sums.\n- Implement retry logic for L1-5 wrong answers with attempt counter.\n- Restart challenge session if the global level is changed during play."
    },
    {
        "hash": "dedc581",
        "date": "2026-07-12",
        "author": "bizzkoot",
        "subject": "feat(ui): add prompt to guided tour button",
        "body": "- Introduce `help.startTourPrompt` i18n key and display text next to the start button\n- Update help block layout to use flexbox `space-between` for alignment\n- Bump service worker cache version to v1.1.4\n- Update changelog with Level 6 release notes and trim history"
    },
    {
        "hash": "6fcb51c",
        "date": "2026-07-12",
        "author": "bizzkoot",
        "subject": "feat(mental-math): add level 6 with multi-step and choice ui",
        "body": "- Introduce Level 6 generating valid multi-step expressions (e.g., A + B - C) within 0-99 range\n- Implement `MentalArithmeticGenerator` for problem generation and multiple-choice distractor creation\n- Add grid-based multiple choice UI for Challenge mode, replacing manual hand inputs\n- Update `arithmeticBuilder` and `teachingOrchestrator` to support guided visualization of chained operations\n- Integrate adaptive difficulty logic increasing problem complexity based on solve time\n- Update i18n, styles, service worker cache, and add e2e tests for new flows"
    },
    {
        "hash": "5af998e",
        "date": "2026-07-12",
        "author": "bizzkoot",
        "subject": "feat(ui): add changelog and reposition badge",
        "body": "- Add `scripts/generateChangelog.js` to populate `js/changelog.js` with recent git history.\n- Implement modal UI with markdown parsing for commit subjects and bodies.\n- Wire changelog generation into `start`, `dev`, and `build` npm scripts.\n- Relocate operand level badge from top-left to top-center of the 3D scene.\n- Update README documentation for current feature set.\n- Add `tests/changelog-modal.spec.js` and bump service worker cache to v1.1.2."
    },
    {
        "hash": "fdc8fed",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "fix(math): prevent zero and negative results",
        "body": "- Ensure subtraction always results in a positive integer.\n- Restrict all generated operands to values greater than zero.\n- Add a tour step highlighting the Operand Level configuration.\n- Initialize Arithmetic mode with a new practice problem.\n- Update test expectations for the new tour and logic constraints."
    },
    {
        "hash": "fa79534",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "chore(spec,sw): document operand-range levels and bump cache version",
        "body": "Spec doc explains the new 5-level system and clarifies the orthogonal\nrelationship to the existing internal 3-level carry/borrow filter.\nBump sw.js cache to v1.1.0 so deployed PWA clients pick up changes."
    },
    {
        "hash": "b925ad1",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "test: pin operand level to L5 in range-dependent specs",
        "body": "Existing tests use operand pairs (47, 38, 87, 12, 42, 17, 73, 21, 89, 83)\nthat exceed the new L1 default of 1-20. Pin the operand level to L5\n(1-99) via addInitScript so behavior is deterministic; clean up\nlocalStorage on test exit."
    },
    {
        "hash": "e467301",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "test(levels): add Playwright spec for operand-level system + TEST_API hooks",
        "body": "9 tests cover: badge rendering, default L1, click-to-open, outside click,\nlocalStorage persistence across reload, Escape closes, practice generator\nrange clamping at L1 and L5, level change resets problem, bilingual labels,\nchallenge generator range clamping.\n\nTEST_API exposes setOperandLevel/getOperandLevel/getOperandLevelMax."
    },
    {
        "hash": "bca71e5",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "feat(i18n): add bilingual labels for operand levels",
        "body": "Adds oplevel.label, oplevel.range, oplevel.option.{1..5}, oplevel.aria.*\nand oplevel.announce to en.json, ms.json, and the embedded LOCALES\nfallback in i18n.js."
    },
    {
        "hash": "377ae89",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "feat(css): style operand-level badge and popover menu",
        "body": "Glassmorphism matching existing overlays (.hm-oplevel-badge, .hm-oplevel-menu).\nActive state, hover, focus-visible, and 600px breakpoint for small viewports."
    },
    {
        "hash": "e98eb4f",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "feat(ui): add top-left operand-level badge + popover menu in 3D scene",
        "body": "Small glass badge in the top-left of the 3D scene shows the current\noperand level and its range. Click to open a popover list of 5 options.\nOutside click and Escape close the menu. Keyboard accessible\n(aria-haspopup/aria-expanded/role=listbox)."
    },
    {
        "hash": "1907d74",
        "date": "2026-07-11",
        "author": "bizzkoot",
        "subject": "feat(levels): add 5-level operand-range state + localStorage persistence",
        "body": "Implements Issue #1 (rebalanced) — five user-facing levels that constrain\nthe operand pool of Practice, Challenge, and Tutorial generators.\n\nFormula: Level N = 1 to min(N*20, 99)\n  L1: 1-20, L2: 1-40, L3: 1-60, L4: 1-80, L5: 1-99\n\nDefault is L1; selection persists to localStorage['hm_operand_level'].\nThe existing internal 3-level carry/borrow logic (already on #levelSel)\nis preserved unchanged and continues to filter problems by carry/borrow\nindependently of the operand range.\n\nCloses #1 (rebalanced)."
    },
    {
        "hash": "9d0de1f",
        "date": "2026-07-10",
        "author": "bizzkoot",
        "subject": "docs(i18n): rewrite help modal copy",
        "body": "- simplify and enliven language in \"How to read Hand Math\" instructions\n- clarify explanations for finger counting and math helper rules\n- add explicit visual cues (emojis) for borrow/carry indicators\n- sync Malay translations with the updated English text\n- bump service worker cache version to v1.0.24"
    },
    {
        "hash": "3100001",
        "date": "2026-07-10",
        "author": "bizzkoot",
        "subject": "feat(tour): expand tour steps and add keyboard navigation",
        "body": "- Expand tour from 3 to 7 steps to provide comprehensive UI guidance.\n- Add keyboard shortcuts (Arrow keys for navigation, Escape to exit).\n- Allow closing the tour by clicking the overlay backdrop.\n- Force 'Tutorial' mode during the tour to ensure element visibility and restore original mode on exit.\n- Refine popup positioning to use dynamic sizing and strict viewport clamping.\n- Update English and Malay translations for new tour content.\n- Adjust service worker cache version to v1.0.23."
    },
    {
        "hash": "bb5bdac",
        "date": "2026-07-10",
        "author": "bizzkoot",
        "subject": "feat(pwa): add install widget and modal",
        "body": "- implement floating widget and modal to guide pwa installation\n- trigger display via beforeinstallprompt or user-agent detection\n- provide platform-specific manual instructions (android/ios)\n- persist widget dismissal state using local storage\n- add installation button to help menu and github link\n- refactor arithmetic tests to stabilize transient cue assertions\n- update en/ms localization strings and bump sw cache version"
    },
    {
        "hash": "aedfbf3",
        "date": "2026-07-05",
        "author": "bizzkoot",
        "subject": "feat(ui): add screen wake toggle",
        "body": "- add screen wake toggle button to the toolbar\n- integrate native Screen Wake Lock API to prevent screen dimming\n- implement silent video loop fallback for iOS compatibility\n- persist user preference in local storage\n- add i18n labels and tooltips for the new control"
    },
    {
        "hash": "d371622",
        "date": "2026-07-05",
        "author": "bizzkoot",
        "subject": "fix(ci): switch to peaceiris/actions-gh-pages to bypass stale pages lock",
        "body": ""
    }
];
