const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const targetFile = path.join(__dirname, '..', 'js', 'changelog.js');

try {
    // Run git log to format the output with markers for easy parsing
    const output = execSync('git log -n 30 --pretty=format:"COMMIT_START%n%h%n%ad%n%an%n%s%n%b%nCOMMIT_END" --date=short', { encoding: 'utf-8' });
    
    const commits = [];
    const rawCommits = output.split(/COMMIT_START\r?\n/);

    for (const raw of rawCommits) {
        if (!raw.trim()) continue;
        
        // Find the index of COMMIT_END marker to isolate this commit block
        const cleanRaw = raw.split(/COMMIT_END/)[0].trim();
        const lines = cleanRaw.split(/\r?\n/);
        
        if (lines.length >= 4) {
            const hash = lines[0].trim();
            const date = lines[1].trim();
            const author = lines[2].trim();
            const subject = lines[3].trim();
            const body = lines.slice(4).join('\n').trim();
            
            commits.push({
                hash,
                date,
                author,
                subject,
                body
            });
        }
    }

    const content = `// This file is auto-generated by scripts/generateChangelog.js. Do not edit directly.
window.HM_CHANGELOG = ${JSON.stringify(commits, null, 4)};
`;

    fs.writeFileSync(targetFile, content, 'utf-8');
    console.log(`Successfully generated changelog with ${commits.length} commits at ${targetFile}`);
} catch (error) {
    console.error('Error generating changelog:', error.message);
    // If not in a git repository or git command fails, write an empty array to prevent app crash
    const fallback = `// Fallback file - generation failed or not in git repo
window.HM_CHANGELOG = [];
`;
    fs.writeFileSync(targetFile, fallback, 'utf-8');
}
